version: "3.7"

services:
  db:
    container_name: todoon_postgresql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USUARIO}
      - POSTGRES_PASSWORD=${DB_SENHA}
      - POSTGRES_DB=${DB_NOME}
    volumes:
      - ./src/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    container_name: todoon_redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379 # Tornando o Redis acessível a outros containers na rede
    networks:
      - app-network

  web:
    container_name: todoon_app
    build: .
    command: daphne -b 0.0.0.0 -p 8000 project.asgi:application # Usando Daphne para ASGI
    ports:
      - 8000:8000
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - redis
    restart: always
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
