version: "3.7"

services:
  db:
    container_name: todoon_postgresql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USUARIO}
      - POSTGRES_PASSWORD=${DB_SENHA}
      - POSTGRES_DB=${DB_NOME}
    volumes:
      - ./src/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  web:
    container_name: todoon_app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
