from todo.serializers.ProjetoSerializer import UsuarioSerializer
from todo.serializers.ProjetoSerializer import ProjetoSerializer
from todo.serializers.QuadroSerializer import QuadroSerializer
from todo.serializers.ListaSerializer import ListaSerializer
from todo.serializers.CartaoSerializer import CartaoSerializer
from todo.serializers.EtiquetaSerializer import EtiquetaSerializer
from todo.serializers.AtividadeSerializer import AtividadeSerializer
from todo.serializers.ListaMembrosSerializer import ListaMembrosSerializer
