# Generated by Django 5.1 on 2024-08-22 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_etiqueta_lista_remove_tarefas_usuario_cartao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='membros',
        ),
        migrations.CreateModel(
            name='ListaMembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('membros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_projeto', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.projeto', verbose_name='Projeto')),
            ],
        ),
    ]
