# Generated by Django 5.1 on 2024-08-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_projeto_membros_listamembros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='quadro',
        ),
        migrations.AddField(
            model_name='lista',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='todo.projeto'),
            preserve_default=False,
        ),
    ]
